name: we_care
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.5.3'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  intl:
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/appLogo.png'

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: fontFamily
      fonts:
        - asset: assets/fonts/BalooThambi-Regular.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
