name: we_care
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: fontFamily
      fonts:
        - asset: assets/fonts/BalooThambi-Regular.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
